### ISSUE TITLE
Bluetooth Firmware - wget returns a webpage

### ISSUE THREAD

**Issue by KyleHarrisUMD** [hg8/bluetooth-firmware-XPS13-9343#2]
As someone already noted, the bluetooth fix you've provided for the XPS13 running ubuntu doesn't work. This is because the provided wget request returns a webpage rather than the actual driver. I've attached the correct file for you in case you've lost it. Also - it may just be easier if your wget request resolves to your website with the action of a file download. Either way thank you for your work with the XPS!

[BCM20702A1-0a5c-216f.hcd.zip](https://github.com/hg8/bluetooth-firmware-XPS13-9343/files/338593/BCM20702A1-0a5c-216f.hcd.zip)

**Comment by hg8** [comment]
You are right! Well spotted thanks. Github changed their layout. I will fix this as soon as possible (tonight hopefully).
